name: 'Build and publish'

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore: 
      - '**.md'
  pull_request:
    paths-ignore: 
      - '**.md'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set matrix data
        id: set-matrix
        run: echo "matrix=$(jq -c . < ./matrix.json)" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: configure
    strategy:
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Define Docker tag
        uses: actions/github-script@v7
        id: docker-tag
        with: 
          result-encoding: string
          script: return "${{ secrets.DOCKERHUB_USERNAME }}/playwright-testbox:node-${{ matrix.node-version }}-playwright-${{ matrix.playwright-version }}"
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build test image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          build-args: | 
            NODE_VERSION=${{ matrix.node-version }}
            PLAYWRIGHT_VERSION=${{ matrix.playwright-version }}
          tags: ${{ steps.docker-tag.outputs.result }}-test
      - name: Run NPM on test image
        run: docker run --rm ${{ steps.docker-tag.outputs.result }}-test npm --version
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: | 
            NODE_VERSION=${{ matrix.node-version }}
            PLAYWRIGHT_VERSION=${{ matrix.playwright-version }}
          tags: ${{ steps.docker-tag.outputs.result }}
          provenance: false #https://github.com/docker/build-push-action/issues/820
          platforms: linux/amd64,linux/arm64/v8